### ISSUE TITLE
Question on NML computation

### ISSUE THREAD

**Issue by ghost** [falkcarl/ockhamSEM#23]
Hi, 

Thank you for this interesting project and providing such a helpful R package! 

When looking at the source code, I noticed that you compute the NML as -2*Log-Normalized Maximum Likelihood. I am just curious: What is the rationale for computing -2 times the log-NML? Thanks!

**Comment by falkcarl** [comment]
Thanks!

NML is currently experimental and I would not yet recommend its use. There are numerical reasons (avoiding underflow) for computing it this way; also -2log part also shows up elsewhere in the literature on NML and gives it a flavor similar to other information criteria that are -2*log likelihood + a penalty (or reward) based on "parsimony".

**Comment by falkcarl** [comment]
If there's no more follow-up on this, I'll close the issue

**Comment by iwoasned** [comment]
Thanks so much for your response! May I ask why you do not yet recommend the use of NML?

**Comment by falkcarl** [comment]
It has not yet been studied extensively, and there will likely be additional changes to computing it to result in better numerical stability

----
Carl F. Falk, Assistant Professor
Quantitative Psychology and Modelling
Department of Psychology, McGill University
2001 McGill College, Room 753
Montreal, QC H3A 1G1, Canada
http://www.psych.mcgill.ca/perpg/fac/falk/


________________________________

**Comment by iwoasned** [comment]
Ok, that seems to match my previous experience with NML in the SEM context, as I also sometimes encountered instable NML values. I was wondering whether it might be possible to implement a Monte Carlo approach with importance sampling. Have you thought about such a procedure as an alternative way of computing it?

**Comment by falkcarl** [comment]
I haven't tried that yet. Can I ask who I'm speaking with?

----
Carl F. Falk, Assistant Professor
Quantitative Psychology and Modelling
Department of Psychology, McGill University
2001 McGill College, Room 753
Montreal, QC H3A 1G1, Canada
http://www.psych.mcgill.ca/perpg/fac/falk/


________________________________
